# original author: Godot Engine contributors
# source: https://github.com/godotengine/godot/blob/master/.github/workflows/javascript_builds.yml
#
# * modified *

name: Build
on: [push, pull_request, workflow_dispatch]

env:
  GODOT_BASE_BRANCH: '3.4'
  SCONSFLAGS: verbose=yes tools=no debug_symbols=no use_lto=yes javascript_eval=no disable_3d=yes disable_advanced_gui=yes
  EM_VERSION: 2.0.27
  EM_CACHE_FOLDER: "emsdk-cache"
  PYTHON_VERSION: 3.8.10

jobs:
  min-wasm:
    # https://github.com/godotengine/godot/issues/31123
    runs-on: "windows-2022"
    name: Godot wasm

    steps:
      - uses: actions/checkout@v2

      # Additional cache for Emscripten generated system libraries
      - name: Load Emscripten cache
        id: javascript-template-emscripten-cache
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{runner.os}}

      - name: Set up Emscripten latest
        uses: mymindstorm/setup-emsdk@v10
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Setup scons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version

      - name: Clone Godot
        run: |
          git clone https://github.com/godotengine/godot -b ${{env.GODOT_BASE_BRANCH}}
          mv custom.py godot/custom.py
          
      - name: Compilation
        run: |
          cd godot
          scons p=javascript target=release --jobs=2 ${{env.SCONSFLAGS}}
          ls -l bin/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: "${{ github.job }}"
          path: "godot/bin/*"